### ISSUE TITLE
Hi, worked ok for my yun, was wondering where firmware that was uploaded came from?

### ISSUE THREAD

**Issue by pwr33** [arduino/yun-go-updater#10]
Nice, worked OK. (were you sponsored by google to use go?)
was wondering where the firmware came from? I tried originally to upload openwrt latest via luci, and then via sysupgrade but no dice, your updater worked OK, still I was wondering where new firmware came from that was uploaded? 
did not know how to contact you other than issue?
I mean nice that you even have the endpoints for web access to gpio etc... but myself do not need that, would rather just be on latest openwrt with bridge working but was wondering if this firmware will now let me upload openwrt latest and for benefit of any yun users a page with explanation of firmware update  (along with lede which is layer above firmware?) and being able for anyone to upgrade to latest secure wireless router with addtion of arduino comms simply through bridge...

I mean the yun as you (post lede update) present it is cool, maybe even better with stuff any more advanced user does not need removed and just the crucial stuff?

**Comment by facchinm** [comment]
No sponsoring by google unluckily :smile: just a very convenient language to write standalone cross-platform utilities :wink: 

The binaries were generated by a combination of
https://github.com/arduino/lede-yun and https://github.com/arduino/openwrt-arduino-packages . If you just need to port the patches to openwrt master, here they are
https://github.com/arduino/lede-yun/commits?author=facchinm
https://github.com/arduino/lede-yun/commit/a3cf57fdfa68f317a0f03f259b912ad59e4bff1d

Some users are already producing updated builds on this base and you can find the discussion [here](https://github.com/arduino/lede-yun/issues/4). Cheers!
