### ISSUE TITLE
No serial port suitable for updating Yun

### ISSUE THREAD

**Issue by IronFist16** [arduino/yun-go-updater#13]
Hello Team,

In trying to upgrade my Yun Shiled v1.0 firmware (installed over Arduino Mega2560), I'm faced with the below message after running the script for upgrade:

"No serial port suitable for updating Yun" 

Though I have the usb cable connected between the Arduino Mega2560 and my Laptop?

Any idea on how to fix this?

**Comment by IronFist16** [comment]
Actually I thought it was because I forgot the jumper on the ISP reset pins, but after removing it, the USB is detected by the script but same message:

Found port: /dev/ttyACM0
USB ID     2341:0042
USB serial 758343436393517082D1
2020/05/16 04:41:25 No serial port suitable for updating Yun

**Comment by facchinm** [comment]
Hi @IronFist16 ,
yun shield is unfortunately not supported by latest fw images, I'm sorry. While you can load them anyway (via sysupgrade method) you'd be missing some functionalities that can be found in default fw.
