### ISSUE TITLE
install packages

### ISSUE THREAD

**Issue by ilovegalya** [arduino/yun-go-updater#2]
I can't install any packages. http://downloads.arduino.cc is unavailable. From this source http://downloads.lede-project.org/snapshots/targets/ar71xx/generic/packages I can't install packages as well because of different versions of kernel

**Comment by facchinm** [comment]
The opkg feed looks online, maybe it was a temporary issue with our download servers. Could you retry now and report back (and close the issue if it is fixed) ? Thanks

**Comment by facchinm** [comment]
PS: in case the problem is still there, could you move the issue to https://github.com/arduino/lede-yun and close this one? Thanks

**Comment by ilovegalya** [comment]
Oh yeah, sorry. I forgot close this topic. Really the issue has gone without any interaction from my side. The remote server had become available after a hour or less. Now everything is perfect. I’m very satisfied by this firmware. Thank you
