### ISSUE TITLE
Could not get your IP address, check your network connection - OSX

### ISSUE THREAD

**Issue by mandria** [arduino/yun-go-updater#3]
Hi,
thanks a lot for your work and this update,
i'm trying to use the tool, all working good since this point.

Could not get your IP address, check your network connection

i get this errror but i'm sure that i have the ip as the ifconfig said
en0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	options=10b<RXCSUM,TXCSUM,VLAN_HWTAGGING,AV>
	ether 40:6c:8f:48:fc:c8 
	inet 10.0.1.11 netmask 0xffffff00 broadcast 10.0.1.255
	media: autoselect (1000baseT <full-duplex>)
	status: active

it's possible to have a interactive step where if the script can't find the ip i can input it manually?

**Comment by facchinm** [comment]
Hi @mandria ,
there is no such functionality at the moment but it's a great idea! I'll try fixing it early tomorrow :wink:

**Comment by mandria** [comment]
yep, great!

**Comment by facchinm** [comment]
I added a couple of cli switches (`-serverip` and `-boardip`) to force ip addresses without any discover phase; the UI changed a bit, so the user must now confirm the autodiscovered IP addresses by simply pressing Enter or Y. How does it look to you?

**Comment by mandria** [comment]
sounds really good, i'll give  a try today and let you know

**Comment by mandria** [comment]
all worked like a charm!!!!

```
sudo ./yun-go-updater -serverip 10.0.0.11 -boardip 10.0.0.33
Password:
Using user provided 10.0.0.11 as server address and 10.0.0.33 as board address
Found port: /dev/cu.usbmodem1421
USB ID     2341:8041
USB serial 
Using it
Restarting in bootloader mode
Get port list before reset
Wait for the port to disappear
Wait for the port to reappear
Found upload port:  /dev/cu.usbmodem1421
Flashing with command:/Users/xx/Downloads/osx/avr/bin/avrdude -C/Users/xx/Downloads/osx/avr/etc/avrdude.conf -v -patmega32u4 -cavr109 -P/dev/cu.usbmodem1421 -b57600 -D -Uflash:w:/Users/xx/Downloads/osx/avr/YunSerialTerminal.ino.hex:i
Wait for the port to disappear
Wait for the port to reappear
Found upload port:  /dev/cu.usbmodem1421
Rebooting the board
Using stop command: ard
Got shell: arduino
Setting up IP addresses
Flashing sysupgrade image
10485764 bytes sent
All done! Enjoy your updated Yun
```
