### ISSUE TITLE
[downloads.arduino.cc] Links Broken

### ISSUE THREAD

**Issue by isantolin** [arduino/yun-go-updater#5]
@facchinm 
Links from page https://forum.arduino.cc/index.php?topic=515869.0 Broken. Can you reupload the files?

https://downloads.arduino.cc/openwrtyun/17.11/yun-go-updater-windows.zip

https://downloads.arduino.cc/openwrtyun/17.11/yun-go-updater-osx.tar.gz

https://downloads.arduino.cc/openwrtyun/17.11/yun-go-updater-linux64.tar.gz

https://downloads.arduino.cc/openwrtyun/17.11/yun-go-updater-linux32.tar.gz

https://downloads.arduino.cc/openwrtyun/17.11/yun-go-updater-linuxarm.tar.gz

**Comment by facchinm** [comment]
Done, sorry for the inconvenience but the deploy job removed some links last time the packages were updated.
