### ISSUE TITLE
[YunDiskSpaceExpander.ino] opkg_install_cmd: Cannot install package dosfstools.

### ISSUE THREAD

**Issue by bgerd** [arduino/yun-go-updater#7]
Hey, Trying to run YunDiskSpaceExpander.ino for the first time in a while...

The `dosfstools` package is no longer available after an `opkg update`, which pulls from http://downloads.arduino.cc/openwrtyun/1/packages/Packages.gz. I checked Packages.gz and it is in fact missing. 

The result is you can't run `mkfs.fat`

**Comment by bgerd** [comment]
scratch that. i just realized i need to run the older YunDiskSpaceExpander for v1.5.2

**Comment by facchinm** [comment]
Yup, no worry :slightly_smiling_face: For reference, the updated sketch is here https://github.com/arduino/yun-go-updater/blob/master/YunDiskSpaceExpander/YunDiskSpaceExpander.ino
