### ISSUE TITLE
[YunDiskSpaceExpander.ino] Installation of kmod-fs-ext4 fails

### ISSUE THREAD

**Issue by jawobar** [arduino/yun-go-updater#8]
Hey, my Yun rev. 2 came with LEDE 17.11 (r5461-ce9089c) preinstalled. Unfortunately, I can't use my microSD because YunDiskSpaceExpander.ino fails to finish successfully.
```
root@Yun:~# opkg install kmod-fs-ext4
Installing kmod-fs-ext4 (4.9.91-1) to root...
Downloading http://downloads.arduino.cc/openwrtyun/17.11/packages/targets/ar71xx/generic/packages/kmod-fs-ext4_4.9.91-1_mips_24kc.ipk
Collected errors:
 * satisfy_dependencies_for: Cannot satisfy the following dependencies for kmod-fs-ext4:
 * 	kernel (= 4.9.91-1-272855890423efd820cc7f0277de710b) * 	kernel (= 4.9.91-1-272855890423efd820cc7f0277de710b) * 
 * opkg_install_cmd: Cannot install package kmod-fs-ext4.
```
```
root@Yun:~# uname -a
Linux Yun 4.9.65 #0 Mon Dec 4 16:26:08 2017 mips GNU/Linux
```
I saw there is r6773+1-8dd3a6e image available, but I am not sure what versions it contains and if I can use YunGoUpdater with rev. 2 board in the first place. Please advise.

**Comment by facchinm** [comment]
Hi @jawobar,
it's very strange that you received a Yun rev2 with a 5xxx firmware. @akash73 can you check if some boards have been shipped with that firmware?
Anyway, you can safely update to any 6xxx firmware, using sysupgrade image or yun-go-updater, your choice, since the bootloader is already ok for all yun rev2 boards.

**Comment by jawobar** [comment]
Hi @facchinm ,
thank you for your help. I have successfully updated with sysupgrade and all issues are gone. Cool! I'm closing the issue :)
As of preinstalled firmware, it's very interesting because I got my board from an authorised distributor. Anyway, I am happy I didn't have to flash the bootloader myself ;)
