### ISSUE TITLE
Sometimes memory is increased, sometimes not

### ISSUE THREAD

**Issue by lucar91** [arduino/yun-go-updater#9]
Hi,
I have an arduino yun with lede-17.01.6.

Since your sketch was not working, i took the following lines from your code:
```
mkdir -p /mnt/sda1
mount /dev/sda1 /mnt/sda1
mkdir -p /mnt/sda1/arduino/www

rsync -a --exclude=/mnt/ --exclude=/www/sd /overlay/ /mnt/sda1/
umount /dev/sda?
rm -rf /mnt/sda?

  uci add fstab mount 
  uci set fstab.@mount[0].target=/overlay 
  uci set fstab.@mount[0].device=/dev/sda1
  uci set fstab.@mount[0].fstype=ext4 
  uci set fstab.@mount[0].enabled=1 
  uci set fstab.@mount[0].enabled_fsck=0
  uci set fstab.@mount[0].options=rw,sync,noatime,nodiratime 
 uci commit 
```

it works for me, and at the first reboot i can see the expanded memory.

But sometimes, when i started the arduino, the memory is not expanded and i have this error
```
>> dmesg | grep err
[    5.456442] usb 1-1: device descriptor read/64, error -32
[    5.686395] usb 1-1: device descriptor read/64, error -32
[   15.022002] blk_update_request: I/O error, dev sda, sector 4550474
[   15.028723] EXT4-fs (sda1): error loading journal
[   15.032395] block: extroot: mounting /dev/sda1 (ext4) on /tmp/extroot/overlay failed: 5 (I/O error)
```
Would you know where the problem is?

**Comment by facchinm** [comment]
The error probably originates from a bad sdcard. Anyway, I strongly advise you to update the yun firmware to the latest available so the expander sketch should work out of the box and drivers/kernel have been updated too.

**Comment by lucar91** [comment]
Hi, thanks for your reply.
I downloaded and installed OPENWRT-YÚN 1.5.3 UPGRADE IMAGE, but the problem remains. 

[   31.930000] end_request: I/O error, dev sda, sector 4456738
[   31.930000] EXT4-fs (sda1): error loading journal

I don't understand.
I'll try to change my SD card...

Meanwhile, thanks a lot for your help.

**Comment by facchinm** [comment]
Sorry, latest image is ledeyun-17.11-r6773+1-8dd3a6e-ar71xx-generic-arduino-yun-squashfs-sysupgrade.bin and you can grab it here https://github.com/arduino/yun-go-updater/tree/master/tftp . The instructions on the website are not updated .

**Comment by lucar91** [comment]
Hi, sorry, I have not had time to try. Meanwhile, I thank you for the answers. If you prefer you can close the discussion and if one day I will deal with the problem again, I will open it again, if possible.

**Comment by facchinm** [comment]
No problem, I'm closing the issue in the meantime, feel free to reopen if needed
